// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOOMTcvbegLkiP1QcsJQcq9hwY7reV-RI',
    appId: '1:882015741621:web:e3fb03a076a9a2004780fc',
    messagingSenderId: '882015741621',
    projectId: 'inovact-social-cd502',
    authDomain: 'inovact-social-cd502.firebaseapp.com',
    storageBucket: 'inovact-social-cd502.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Ed2OwUXCYaVuPTOyKRn4SLCZ7_o75sg',
    appId: '1:882015741621:android:0567013d6b9d62574780fc',
    messagingSenderId: '882015741621',
    projectId: 'inovact-social-cd502',
    storageBucket: 'inovact-social-cd502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPidT-ekaPtsLFW3WIiuoy3FHfG4hMZf8',
    appId: '1:882015741621:ios:ae0d30c59236ff744780fc',
    messagingSenderId: '882015741621',
    projectId: 'inovact-social-cd502',
    storageBucket: 'inovact-social-cd502.firebasestorage.app',
    iosBundleId: 'com.example.inovactSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPidT-ekaPtsLFW3WIiuoy3FHfG4hMZf8',
    appId: '1:882015741621:ios:ae0d30c59236ff744780fc',
    messagingSenderId: '882015741621',
    projectId: 'inovact-social-cd502',
    storageBucket: 'inovact-social-cd502.firebasestorage.app',
    iosBundleId: 'com.example.inovactSocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOOMTcvbegLkiP1QcsJQcq9hwY7reV-RI',
    appId: '1:882015741621:web:a1a2ca52d7242ad94780fc',
    messagingSenderId: '882015741621',
    projectId: 'inovact-social-cd502',
    authDomain: 'inovact-social-cd502.firebaseapp.com',
    storageBucket: 'inovact-social-cd502.firebasestorage.app',
  );
}
